### ISSUE TITLE
JavaScript SPA Agents should provide the Agent Session Id and Loupe Session Id (if available) on all requests

### ISSUE THREAD

**Issue by DaveSussman** [GibraltarSoftware/Loupe.JavaScript#1]
Client agents need to include the agent session id as a header for all requests. While the agent session id is already included as part of the log message payload, and while it does not need to be included as a header, it should be for consistency. Additionally, for client frameworks (such as Angular and React), the agent should automatically add this header to all API requests. The rationale for this is to allow the Loupe back end to correlate requests using a consistent header.

Implementation for Angular should include an HttpInterceptor to automatically set the agent session id header upon each request. React should include similar functionality.

**Comment by DaveSussman** [comment]
The header should be named: loupe-agent-sessionId

**Comment by kendallmiller** [comment]
It's also important to include the server-provided Loupe Session Id if available. The Loupe agent that integrates with the web server can provide a consistent session Id in a cookie for each request which is intended to correlate server requests from the same client.  So, we want to be sure either the cookie is echoed back to the same server that generated it (if we keep the cookie) or better yet provide a second header with the session Id.  If the client is interacting with multiple servers it'd be best to have it set *both* the Loupe Session Id and Loupe Agent Session Id and send them in headers to the server.

Why two ID's?  The Loupe Session Id should be consistent if the user splits off to a new window in the same browser but the Loupe Agent Session Id should be reset every time the user reinitializes the SPA. That way on the server you can tell the difference between multiple client activity streams interacting with the server but also know they started from the same initial point.  Using a cookie may be the best/easiest way to achieve this.

The Loupe Session Id should not be persisted so if the user closes the browser, opens it again, and logs in they get a new session id.
